### PR TITLE
Added character count listener

### PR DESCRIPTION
**Pull request by Seqi**

### CODE REVIEW

**Comment by nokonoko** [comment]
Any diff in using this one vs the one there is now in includes/js/board.js? Does this one also work for pasting?

**Comment by Seqi** [comment]
Yea, demo here: https://i.imgur.com/RDaZZ5f.gif

**Comment by nokonoko** [comment]
Nice, think you can edit it so it works with the current setup where the counter is above the textbox?

**Comment by Seqi** [comment]
You want the input style counter too or just move whats there already (X/Y)

**Comment by nokonoko** [comment]
Move the script to includes/js/board.js and replace the current and then make it work with the style its using now.

Like so: https://files.catbox.moe/98c6u7.png

Would be very kind of u :3

**Comment by Seqi** [comment]
i got u

i dont know php that well so lemme know if shit aint right

**Review by nokonoko — APPROVED** [review]

**Pull request merged**
